apiVersion: v1
kind: Service
metadata:
  name: {{ include "elevator.fullname" . }}
  labels:
    app: {{ include "elevator.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 8081
      targetPort: 8081
      name: metrics
  selector:
    app: {{ include "elevator.name" . }}
